name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version from tag
        id: extract_version
        run: |
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Build and push frontend container
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            "uhhlt/corpus_browser_frontend:${{ steps.extract_version.outputs.version }}"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
